---
- name: Implementing when condition
  hosts: all
  become: true # Ensure permission to access /etc/passwd
  vars:
   a: 10
  tasks:
   - name: Copy passwd file if condition met
     ansible.builtin.copy:
      src: /etc/passwd
      dest: /temp
     when: a == 10
...
# ####################################################
---
- name: Error handling and OS-specific install
  hosts: all
  become: yes # Added -b to the command, so the play needs this or tasks need become: yes
  tasks:
    - block:
        - name: Install git using apt on Debian/Ubuntu servers (This task will fail on Red Hat)
          ansible.builtin.apt:
            name: git
            state: present
            update_cache: yes
          when: ansible_facts['os_family'] == "Debian"

      rescue:
        - name: Install git using yum/dnf on RedHat/CentOS servers
          ansible.builtin.yum: # or dnf
            name: git
            state: present
          # Note: update_cache is not a parameter for yum/dnf.
          when: ansible_facts['os_family'] == "RedHat"
          
      always:
        - name: Display Success msg (This runs even if install failed on all OS checks)
          ansible.builtin.debug:
            msg: "Git installation attempt completed."