# include module is call other play book in main playbook , i.e other play book is child play book, it might a any module
# vim install.yml
---
- name: install apache2
  ansible.builtin.apt:
   name: apache2
   state: present
   update_cache: yes
...

# vim  index.yml
---
- name: Edit the index.html
  ansible.builtin.copy:
   content: <h1> welocme cicdclouds.com </h1>
   dest: /var/www/html/index.html
...
 # vim restart.yml
---
- name: apache2 server restart
  ansible.builtin.service:
   name: apache2
   state: restarted
...
#  vim check_url.yml
---
- name: check apache2 servce response
  ansible.builtin.uri:
  url: "{{item}}"
  status_code: 200
...

# vim configure.yml
---
- name: configure apache2 multimodule as child
  hosts: all
  become: yes
  tasks:
    - name: call install child playbook
      include: install.yml
    - name: Edit the index.html child playbook
      include: index.yml
    - name: call restart playbook
      include: restart.yml
    - name: check the response check_url 
      include: check_url.yml
... 

# above yml file modified 
---
- name: Configure Apache2 with multiple child modules
  hosts: all
  become: yes
  tasks:
    - name: Include child playbooks for Apache setup
      ansible.builtin.include_tasks: "{{ item }}"
      loop:
        - install.yml
        - index.yml
        - restart.yml
        - check_url.yml
# ---
#- import_playbook: install.yml
#- import_playbook: index.yml
#- import_playbook: restart.yml
#- import_playbook: check_url.yml



